load_paths:
  - app/assets/javascripts
  - test/javascripts/src
  - test/javascripts/vendor
  - test/javascripts/fixtures

logical_paths:
  - local_time.js
  - test.js

plugins:
  sauce_labs:
    test_config:
      time_zone: Central
      max_duration: 300
    browsers:
      chrome:
        version: -2
        os: Mac, Windows, Linux
      firefox:
        version: -2
        os: Mac, Windows, Linux
      safari:
        version: -2
      ie:
        version: -3
      iphone:
        version: -2
      android:
        version: -2
