language: ruby
cache: bundler
before_install:
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX1VTRVJOQU1FPWJhc2VjYW1wX2xvY2FsX3RpbWUK`
  - true && `base64 --decode <<< ZXhwb3J0IFNBVUNFX0FDQ0VTU19LRVk9ZWM5Y2QyMjMtOTFjNS00NmRkLWJmNDktZWIyYmZiY2NjYzMzCg==`
